image:
  file: .gitpod.Dockerfile

tasks:
  - before: printf "\n[settings]\napi_key = $WAKA_TIME_API_KEY\n" > ~/.wakatime.cfg && chmod +x mono.sh && ./mono.sh
    

vscode:
  extensions:
    - muhammad-sammy.csharp